## District Data

In [1]:
import pandas as pd
import numpy as np
import math

In [11]:
District = pd.read_csv('AllUSDistricts.CSV')
AllDistricts = District[["state_code","district"]]
AllDistricts = AllDistricts.rename(columns={'state_code':'State','district':'District'})
AllDistricts["State-District"] = AllDistricts["State"].map(str) + "-" + (AllDistricts["District"]).map(str)
AllDistricts.head()

  State  District State-District
0    AK         0           AK-0
1    AL         1           AL-1
2    AL         2           AL-2
3    AL         3           AL-3
4    AL         4           AL-4

In [12]:
House = pd.read_csv("NASAHouseCommittees.csv")
House = House.drop(["Name"],axis=1)
House["HouseCommitties"] = House["House Science, Space and Technology Committee"] + House["House Space and Aeronautics Subcommittee"] + House["House CJS"]
House

,District,State,"House Science, Space and Technology Committee",House Space and Aeronautics Subcommittee,House CJS,HouseCommitties
0,7,CA,1,1,0,2
1,5,AZ,1,0,0,1
2,16,OH,1,0,0,1
3,4,UT,1,0,0,1
4,11,IL,1,0,0,1
5,8,FL,1,1,0,2
6,30,CA,1,0,0,1
7,14,MI,0,0,1,1
8,36,TX,1,1,0,2
9,13,FL,1,1,1,3
10,17,PA,1,0,0,1
11,3,IL,1,0,0,1
12,8,VA,1,1,0,2
13,1,HI,0,0,1,1
14,7,CO,1,1,0,2
15,30,TX,2,0,0,2
16,19,FL,1,0,0,1
17,3,OK,1,0,0,1
18,6,NY,0,0,1,1
19,3,NC,1,0,0,1
20,11,MI,1,0,0,1
21,4,AL,0,0,1,1
22,3,WA,1,0,0,1
23,10,VA,1,1,0,2
24,9,CA,1,0,0,1
25,4,IN,1,0,0,1
26,15,NY,0,0,2,2
27,5,OK,1,2,0,3
28,7,TX,1,0,0,1
29,9,OH,0,0,1,1
30,2,AL,0,0,1,1
31,8,PA,0,0,1,1
32,27,TX,1,0,0,1
33,6,FL,1,1,0,2
34,11,NJ,1,0,0,1
35,5,AL,1,1,0,2
36,20,NY,1,0,0,1
37,22,TX,1,1,0,2
38,5,SC,1,0,0,1
39,14,TX,1,0,0,1
40,1,KS,1,0,0,1
41,6,IL,1,0,0,1
42,9,TN,1,0,0,1
43,4,MI,0,0,1,1
44,1,OR,1,0,0,1
45,14,GA,0,0,1,1
46,12,OH,1,0,0,1
47,19,CA,1,1,0,2

In [13]:
Centers = pd.read_csv('NASACenters_District.csv')
CentName = pd.read_csv('NASACenters_District.csv')
Centers = Centers.drop(["Zip"], axis=1)
Centers["Center"] = 1 
Centers = Centers.groupby(["State","District"]).sum()
Centers

                Center
State District
AL    5              1
CA    18             1
      23             1
      27             1
DC    1              1
FL    8              1
MD    3              1
      5              1
MS    4              1
OH    16             1
TX    36             1
VA    3              1

In [14]:
ConHouse = pd.read_csv("District_Cleaned_Nasa_Data.csv")
ConHouse19 = ConHouse[ConHouse.Year == 2019].reset_index()
ConHouse19 = ConHouse19.drop(["Year","index"],axis=1)
ConHouse19

    State  District         Award
0      AK         0  1.178197e+05
1      AL         1  1.455900e+02
2      AL         2  1.889476e+04
3      AL         3  1.154495e+04
4      AL         4  9.295380e+02
5      AL         5  1.082422e+07
6      AL         6  9.181000e+01
7      AL         7  9.760392e+03
8      AR         2  7.246241e+03
9      AR         3  5.272901e+03
10     AZ         1  2.503109e+04
11     AZ         2  5.096741e+04
12     AZ         3  7.080883e+05
13     AZ         4  2.237630e+02
14     AZ         5  4.995594e+05
15     AZ         6  3.198048e+03
16     AZ         7  4.518689e+03
17     AZ         8  8.697151e+03
18     AZ         9  2.394657e+05
19     CA         1  3.851691e+03
20     CA         2  2.385706e+04
21     CA         3  3.478897e+04
22     CA         4  4.000453e+03
23     CA         5  1.478749e+05
24     CA         6  3.407680e+02
25     CA         7  2.309704e+03
26     CA         8  9.291570e+02
27     CA         9  1.725590e+02
28     CA        11  3.196450e+02
29     CA        12  1.576064e+04
..    ...       ...           ...
387    VA         3  4.351544e+05
388    VA         4  9.155880e+02
389    VA         5  2.260495e+04
390    VA         6  5.999614e+03
391    VA         7  2.609913e+03
392    VA         8  5.712847e+05
393    VA         9  2.712349e+04
394    VA        10  7.467627e+05
395    VA        11  2.551184e+06
396    VT         0  9.577578e+03
397    WA         1  2.019678e+05
398    WA         2  4.535367e+03
399    WA         3  1.421230e+02
400    WA         4  3.888780e+03
401    WA         5  3.569714e+03
402    WA         6  1.069990e+02
403    WA         7  1.244063e+05
404    WA         8  4.633624e+03
405    WA         9  7.823018e+03
406    WA        10  2.882340e+02
407    WI         1  4.894901e+03
408    WI         2  7.611341e+04
409    WI         3  1.469956e+03
410    WI         4  2.371583e+03
411    WI         5  3.933699e+03
412    WI         6  3.474883e+03
413    WI         7  3.390100e+01
414    WV         1  4.956121e+05
415    WV         2  1.654900e+01
416    WY         0  1.036047e+04

[417 rows x 3 columns]

In [15]:
ACleanDistricts = pd.merge(AllDistricts,Centers, on=["State","District"],how='left')
BCleanDistricts = pd.merge(ACleanDistricts,House, on=["State","District"],how='left')
CCleanDistricts = pd.merge(BCleanDistricts,ConHouse19, on=["State","District"],how='left')
CleanDistricts = pd.merge(CCleanDistricts,CentName, on=["State","District"],how='left')
CleanDistricts = CleanDistricts.fillna(0)
CleanDistricts["NatLog_Award"] = np.where(CleanDistricts['Award']==0, 0.0, np.log(CleanDistricts.Award))
CleanDistricts["Log10_Award"] = np.where(CleanDistricts['Award']==0, 0.0, np.log10(CleanDistricts.Award))
CleanDistricts.Center_Abbreviation.replace(0, np.nan, inplace=True)
CleanDistricts.Center_Name.replace(0, np.nan, inplace=True)
CleanDistricts

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in log

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: divide by zero encountered in log10
  import sys

,State,District,State-District,Center,"House Science, Space and Technology Committee",House Space and Aeronautics Subcommittee,House CJS,HouseCommitties,Award,Zip,Center_Abbreviation,Center_Name,NatLog_Award,Log10_Award
0,AK,0,AK-0,0.0,0.0,0.0,0.0,0.0,1.178197e+05,0.0,NaN,NaN,11.676910,5.071218
1,AL,1,AL-1,0.0,0.0,0.0,0.0,0.0,1.455900e+02,0.0,NaN,NaN,4.980794,2.163132
2,AL,2,AL-2,0.0,0.0,0.0,1.0,1.0,1.889476e+04,0.0,NaN,NaN,9.846640,4.276341
3,AL,3,AL-3,0.0,0.0,0.0,0.0,0.0,1.154495e+04,0.0,NaN,NaN,9.354003,4.062392
4,AL,4,AL-4,0.0,0.0,0.0,1.0,1.0,9.295380e+02,0.0,NaN,NaN,6.834688,2.968267
5,AL,6,AL-6,0.0,0.0,0.0,0.0,0.0,9.181000e+01,0.0,NaN,NaN,4.519721,1.962890
6,AL,5,AL-5,1.0,1.0,1.0,0.0,2.0,1.082422e+07,35824.0,MSFC,Marshall Space Flight Center,16.197297,7.034397
7,AL,7,AL-7,0.0,0.0,0.0,0.0,0.0,9.760392e+03,0.0,NaN,NaN,9.186088,3.989467
8,AR,1,AR-1,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,NaN,NaN,0.000000,0.000000
9,AR,2,AR-2,0.0,0.0,0.0,0.0,0.0,7.246241e+03,0.0,NaN,NaN,8.888238,3.860113
10,AR,3,AR-3,0.0,0.0,0.0,0.0,0.0,5.272901e+03,0.0,NaN,NaN,8.570336,3.722050
11,AR,4,AR-4,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,NaN,NaN,0.000000,0.000000
12,AZ,1,AZ-1,0.0,0.0,0.0,0.0,0.0,2.503109e+04,0.0,NaN,NaN,10.127874,4.398480
13,AZ,2,AZ-2,0.0,0.0,0.0,0.0,0.0,5.096741e+04,0.0,NaN,NaN,10.838942,4.707293
14,AZ,3,AZ-3,0.0,0.0,0.0,0.0,0.0,7.080883e+05,0.0,NaN,NaN,13.470324,5.850087
15,AZ,4,AZ-4,0.0,0.0,0.0,0.0,0.0,2.237630e+02,0.0,NaN,NaN,5.410587,2.349788
16,AZ,5,AZ-5,0.0,1.0,0.0,0.0,1.0,4.995594e+05,0.0,NaN,NaN,13.121482,5.698587
17,AZ,6,AZ-6,0.0,0.0,0.0,0.0,0.0,3.198048e+03,0.0,NaN,NaN,8.070296,3.504885
18,AZ,7,AZ-7,0.0,0.0,0.0,0.0,0.0,4.518689e+03,0.0,NaN,NaN,8.415977,3.655012
19,AZ,8,AZ-8,0.0,0.0,0.0,0.0,0.0,8.697151e+03,0.0,NaN,NaN,9.070751,3.939377
20,AZ,9,AZ-9,0.0,0.0,0.0,0.0,0.0,2.394657e+05,0.0,NaN,NaN,12.386165,5.379243
21,CA,1,CA-1,0.0,0.0,0.0,0.0,0.0,3.851691e+03,0.0,NaN,NaN,8.256268,3.585651
22,CA,2,CA-2,0.0,0.0,0.0,0.0,0.0,2.385706e+04,0.0,NaN,NaN,10.079835,4.377617
23,CA,3,CA-3,0.0,0.0,0.0,0.0,0.0,3.478897e+04,0.0,NaN,NaN,10.457056,4.541442
24,CA,4,CA-4,0.0,0.0,0.0,0.0,0.0,4.000453e+03,0.0,NaN,NaN,8.294163,3.602109
25,CA,5,CA-5,0.0,0.0,0.0,0.0,0.0,1.478749e+05,0.0,NaN,NaN,11.904122,5.169895
26,CA,6,CA-6,0.0,0.0,0.0,0.0,0.0,3.407680e+02,0.0,NaN,NaN,5.831202,2.532459
27,CA,7,CA-7,0.0,1.0,1.0,0.0,2.0,2.309704e+03,0.0,NaN,NaN,7.744875,3.363556
28,CA,8,CA-8,0.0,0.0,0.0,0.0,0.0,9.291570e+02,0.0,NaN,NaN,6.834278,2.968089
29,CA,9,CA-9,0.0,1.0,0.0,0.0,1.0,1.725590e+02,0.0,NaN,NaN,5.150739,2.236938
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
405,VA,5,VA-5,0.0,0.0,0.0,0.0,0.0,2.260495e+04,0.0,NaN,NaN,10.025924,4.354204
406,VA,6,VA-6,0.0,0.0,0.0,0.0,0.0,5.999614e+03,0.0,NaN,NaN,8.699450,3.778123
407,VA,7,VA-7,0.0,0.0,0.0,0.0,0.0,2.609913e+03,0.0,NaN,NaN,7.867072,3.416626
408,VA,8,VA-8,0.0,1.0,1.0,0.0,2.0,5.712847e+05,0.0,NaN,NaN,13.255643,5.756853
409,VA,9,VA-9,0.0,0.0,0.0,0.0,0.0,2.712349e+04,0.0,NaN,NaN,10.208155,4.433346
410,VA,10,VA-10,0.0,1.0,1.0,0.0,2.0,7.467627e+05,0.0,NaN,NaN,13.523503,5.873183
411,VA,11,VA-11,0.0,0.0,0.0,0.0,0.0,2.551184e+06,0.0,NaN,NaN,14.752068,6.406742
412,VT,0,VT-0,0.0,0.0,0.0,0.0,0.0,9.577578e+03,0.0,NaN,NaN,9.167180,3.981256
413,WA,2,WA-2,0.0,0.0,0.0,0.0,0.0,4.535367e+03,0.0,NaN,NaN,8.419661,3.656612
414,WA,1,WA-1,0.0,0.0,0.0,0.0,0.0,2.019678e+05,0.0,NaN,NaN,12.215863,5.305282
415,WA,3,WA-3,0.0,1.0,0.0,0.0,1.0,1.421230e+02,0.0,NaN,NaN,4.956693,2.152664
416,WA,4,WA-4,0.0,0.0,0.0,0.0,0.0,3.888780e+03,0.0,NaN,NaN,8.265851,3.589813
417,WA,5,WA-5,0.0,0.0,0.0,0.0,0.0,3.569714e+03,0.0,NaN,NaN,8.180241,3.552633
418,WA,6,WA-6,0.0,0.0,0.0,0.0,0.0,1.069990e+02,0.0,NaN,NaN,4.672819,2.029380
419,WA,7,WA-7,0.0,0.0,0.0,0.0,0.0,1.244063e+05,0.0,NaN,NaN,11.731308,5.094842
420,WA,8,WA-8,0.0,0.0,0.0,0.0,0.0,4.633624e+03,0.0,NaN,NaN,8.441095,3.665921
421,WA,9,WA-9,0.0,0.0,0.0,0.0,0.0,7.823018e+03,0.0,NaN,NaN,8.964826,3.893374
422,WA,10,WA-10,0.0,0.0,0.0,0.0,0.0,2.882340e+02,0.0,NaN,NaN,5.663773,2.459745
423,WI,1,WI-1,0.0,0.0,0.0,0.0,0.0,4.894901e+03,0.0,NaN,NaN,8.495949,3.689744
424,WI,2,WI-2,0.0,0.0,0.0,0.0,0.0,7.611341e+04,0.0,NaN,NaN,11.239980,4.881461
425,WI,3,WI-3,0.0,0.0,0.0,0.0,0.0,1.469956e+03,0.0,NaN,NaN,7.292988,3.167304
426,WI,4,WI-4,0.0,0.0,0.0,0.0,0.0,2.371583e+03,0.0,NaN,NaN,7.771313,3.375038
427,WI,5,WI-5,0.0,0.0,0.0,0.0,0.0,3.933699e+03,0.0,NaN,NaN,8.277335,3.594801
428,WI,6,WI-6,0.0,0.0,0.0,0.0,0.0,3.474883e+03,0.0,NaN,NaN,8.153316,3.540940
429,WI,7,WI-7,0.0,0.0,0.0,0.0,0.0,3.390100e+01,0.0,NaN,NaN,3.523445,1.530213
430,WI,8,WI-8,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,NaN,NaN,0.000000,0.000000
431,WV,1,WV-1,0.0,0.0,0.0,0.0,0.0,4.956121e+05,0.0,NaN,NaN,13.113549,5.695142
432,WV,2,WV-2,0.0,0.0,0.0,0.0,0.0,1.654900e+01,0.0,NaN,NaN,2.806326,1.218772
433,WV,3,WV-3,0.0,0.0,0.0,0.0,0.0,0.000000e+00,0.0,NaN,NaN,0.000000,0.000000
434,WY,0,WY-0,0.0,0.0,0.0,0.0,0.0,1.036047e+04,0.0,NaN,NaN,9.245752,4.015379

## State Data

In [16]:
States = pd.read_csv('StateList.csv')
States = States.drop(["State","Abbrev"],axis=1)
States = States.rename({"Code":"State"},axis=1)
States

   State
0     AL
1     AK
2     AZ
3     AR
4     CA
5     CO
6     CT
7     DE
8     DC
9     FL
10    GA
11    HI
12    ID
13    IL
14    IN
15    IA
16    KS
17    KY
18    LA
19    ME
20    MD
21    MA
22    MI
23    MN
24    MS
25    MO
26    MT
27    NE
28    NV
29    NH
30    NJ
31    NM
32    NY
33    NC
34    ND
35    OH
36    OK
37    OR
38    PA
39    RI
40    SC
41    SD
42    TN
43    TX
44    UT
45    VT
46    VA
47    WA
48    WV
49    WI
50    WY

In [17]:
StateCenters = Centers
StateCenters = StateCenters.groupby(["State"]).sum()
StateCenters

       Center
State
AL          1
CA          3
DC          1
FL          1
MD          2
MS          1
OH          1
TX          1
VA          1

In [18]:
Senate = pd.read_csv("NASASenateCommittees.csv")
Senate = Senate.drop(["Name"],axis=1)
Senate.sort_values(by=["State"],inplace=True)
Senate["SenateCommittess"] = Senate["Senate Commerce, Science, and Transportation"] + Senate["Senate Aviation and Space Subcommittee"] + Senate["Senate CJS"]
Senate

,State,"Senate Commerce, Science, and Transportation",Senate Aviation and Space Subcommittee,Senate CJS,SenateCommittess
0,AK,1,0,1,2
1,AL,0,0,2,2
2,AR,0,0,1,1
3,AZ,1,1,0,2
4,CA,0,0,1,1
5,CO,1,1,0,2
6,CT,1,0,1,2
7,DE,0,0,1,1
8,FL,1,0,1,2
9,HI,1,1,1,3
10,IL,1,1,1,3
11,IN,1,0,0,1
12,KS,1,1,1,3
13,KY,0,0,1,1
14,LA,0,0,1,1
15,MA,1,0,0,1
16,MD,0,0,1,1
17,ME,0,0,1,1
18,MI,3,1,0,4
19,MN,1,0,0,1
20,MS,1,1,2,4
21,MT,1,1,2,4
22,ND,0,0,1,1
23,NE,1,0,0,1
24,NH,0,0,1,1
25,NM,1,1,1,3
26,NV,1,1,0,2
27,OK,0,0,1,1
28,OR,0,0,1,1
29,RI,0,0,1,1
30,SC,0,0,1,1
31,SD,1,1,0,2
32,TN,1,1,1,3
33,TX,1,2,0,3
34,UT,1,1,0,2
35,VT,0,0,1,1
36,WA,1,0,1,2
37,WI,2,0,1,3
38,WV,1,1,2,4

In [19]:
ConSenate = pd.read_csv("State_Cleaned_Nasa_Data.csv")
ConSenate19 = ConSenate[ConSenate.Year == 2019].reset_index()
ConSenate19 = ConSenate19.drop(["Year","index"],axis=1)
ConSenate19

   State         Award
0     AK  1.178197e+05
1     AL  1.086559e+07
2     AR  1.251914e+04
3     AZ  1.539750e+06
4     CA  4.882194e+07
5     CO  1.951038e+07
6     CT  1.388316e+05
7     DC  7.363195e+05
8     DE  4.352644e+04
9     FL  8.395190e+06
10    GA  9.653787e+04
11    HI  1.443070e+05
12    IA  4.823565e+04
13    ID  2.196155e+04
14    IL  1.264121e+05
15    IN  2.522000e+06
16    KS  6.143124e+04
17    KY  2.946643e+04
18    LA  4.351411e+04
19    MA  1.814553e+06
20    MD  2.134296e+07
21    ME  2.659847e+04
22    MI  2.675584e+05
23    MN  5.763147e+04
24    MO  1.789903e+05
25    MS  3.655517e+06
26    MT  4.995693e+04
27    NC  6.314669e+04
28    ND  1.370819e+04
29    NE  1.373785e+04
30    NH  1.629864e+05
31    NJ  1.014371e+05
32    NM  1.946604e+05
33    NV  1.551171e+05
34    NY  6.941744e+05
35    OH  1.108011e+06
36    OK  2.359539e+05
37    OR  6.633943e+04
38    PA  2.837392e+05
39    RI  2.636338e+04
40    SC  3.833532e+04
41    SD  2.141944e+04
42    TN  4.957076e+04
43    TX  2.748943e+07
44    UT  4.095960e+06
45    VA  7.934596e+06
46    VT  9.577578e+03
47    WA  3.513620e+05
48    WI  9.229234e+04
49    WV  4.956286e+05
50    WY  1.036047e+04

In [20]:
ACleanState = pd.merge(States,StateCenters, on=["State"],how='left')
BCleanState = pd.merge(ACleanState,ConSenate19, on=["State"],how='left')
CleanStates = pd.merge(BCleanState,Senate, on=["State"],how='left')
CleanStates = CleanStates.fillna(0)
CleanStates["NatLog_Award"] = np.where(CleanStates['Award']==0, 0.0, np.log(CleanStates.Award))
CleanStates["Log10_Award"] = np.where(CleanStates['Award']==0, 0.0, np.log10(CleanStates.Award))
CleanStates

,State,Center,Award,"Senate Commerce, Science, and Transportation",Senate Aviation and Space Subcommittee,Senate CJS,SenateCommittess,NatLog_Award,Log10_Award
0,AL,1.0,1.086559e+07,0.0,0.0,2.0,2.0,16.201111,7.036053
1,AK,0.0,1.178197e+05,1.0,0.0,1.0,2.0,11.676910,5.071218
2,AZ,0.0,1.539750e+06,1.0,1.0,0.0,2.0,14.247130,6.187450
3,AR,0.0,1.251914e+04,0.0,0.0,1.0,1.0,9.435014,4.097575
4,CA,3.0,4.882194e+07,0.0,0.0,1.0,1.0,17.703690,7.688615
5,CO,0.0,1.951038e+07,1.0,1.0,0.0,2.0,16.786457,7.290266
6,CT,0.0,1.388316e+05,1.0,0.0,1.0,2.0,11.841017,5.142488
7,DE,0.0,4.352644e+04,0.0,0.0,1.0,1.0,10.681124,4.638753
8,DC,1.0,7.363195e+05,0.0,0.0,0.0,0.0,13.509419,5.867066
9,FL,1.0,8.395190e+06,1.0,0.0,1.0,2.0,15.943170,6.924031
10,GA,0.0,9.653787e+04,0.0,0.0,0.0,0.0,11.477691,4.984698
11,HI,0.0,1.443070e+05,1.0,1.0,1.0,3.0,11.879699,5.159288
12,ID,0.0,2.196155e+04,0.0,0.0,0.0,0.0,9.997048,4.341663
13,IL,0.0,1.264121e+05,1.0,1.0,1.0,3.0,11.747302,5.101788
14,IN,0.0,2.522000e+06,1.0,0.0,0.0,1.0,14.740563,6.401745
15,IA,0.0,4.823565e+04,0.0,0.0,0.0,0.0,10.783854,4.683368
16,KS,0.0,6.143124e+04,1.0,1.0,1.0,3.0,11.025674,4.788389
17,KY,0.0,2.946643e+04,0.0,0.0,1.0,1.0,10.291007,4.469328
18,LA,0.0,4.351411e+04,0.0,0.0,1.0,1.0,10.680840,4.638630
19,ME,0.0,2.659847e+04,0.0,0.0,1.0,1.0,10.188609,4.424857
20,MD,2.0,2.134296e+07,0.0,0.0,1.0,1.0,16.876232,7.329255
21,MA,0.0,1.814553e+06,1.0,0.0,0.0,1.0,14.411350,6.258770
22,MI,0.0,2.675584e+05,3.0,1.0,0.0,4.0,12.497093,5.427419
23,MN,0.0,5.763147e+04,1.0,0.0,0.0,1.0,10.961824,4.760660
24,MS,1.0,3.655517e+06,1.0,1.0,2.0,4.0,15.111748,6.562949
25,MO,0.0,1.789903e+05,0.0,0.0,0.0,0.0,12.095087,5.252830
26,MT,0.0,4.995693e+04,1.0,1.0,2.0,4.0,10.818917,4.698596
27,NE,0.0,1.373785e+04,1.0,0.0,0.0,1.0,9.527910,4.137919
28,NV,0.0,1.551171e+05,1.0,1.0,0.0,2.0,11.951935,5.190660
29,NH,0.0,1.629864e+05,0.0,0.0,1.0,1.0,12.001422,5.212151
30,NJ,0.0,1.014371e+05,0.0,0.0,0.0,0.0,11.527194,5.006197
31,NM,0.0,1.946604e+05,1.0,1.0,1.0,3.0,12.179012,5.289278
32,NY,0.0,6.941744e+05,0.0,0.0,0.0,0.0,13.450478,5.841469
33,NC,0.0,6.314669e+04,0.0,0.0,0.0,0.0,11.053216,4.800351
34,ND,0.0,1.370819e+04,0.0,0.0,1.0,1.0,9.525749,4.136980
35,OH,1.0,1.108011e+06,0.0,0.0,0.0,0.0,13.918077,6.044544
36,OK,0.0,2.359539e+05,0.0,0.0,1.0,1.0,12.371392,5.372827
37,OR,0.0,6.633943e+04,0.0,0.0,1.0,1.0,11.102540,4.821772
38,PA,0.0,2.837392e+05,0.0,0.0,0.0,0.0,12.555811,5.452919
39,RI,0.0,2.636338e+04,0.0,0.0,1.0,1.0,10.179731,4.421001
40,SC,0.0,3.833532e+04,0.0,0.0,1.0,1.0,10.554127,4.583599
41,SD,0.0,2.141944e+04,1.0,1.0,0.0,2.0,9.972054,4.330808
42,TN,0.0,4.957076e+04,1.0,1.0,1.0,3.0,10.811156,4.695226
43,TX,1.0,2.748943e+07,1.0,2.0,0.0,3.0,17.129312,7.439166
44,UT,0.0,4.095960e+06,1.0,1.0,0.0,2.0,15.225512,6.612356
45,VT,0.0,9.577578e+03,0.0,0.0,1.0,1.0,9.167180,3.981256
46,VA,1.0,7.934596e+06,0.0,0.0,0.0,0.0,15.886743,6.899525
47,WA,0.0,3.513620e+05,1.0,0.0,1.0,2.0,12.769572,5.545755
48,WV,0.0,4.956286e+05,1.0,1.0,2.0,4.0,13.113582,5.695156
49,WI,0.0,9.229234e+04,2.0,0.0,1.0,3.0,11.432716,4.965166
50,WY,0.0,1.036047e+04,0.0,0.0,0.0,0.0,9.245752,4.015379

In [21]:
CleanStates.to_csv(r'Cleaned_States19.csv')
CleanDistricts.to_csv(r'Cleaned_Districts19.csv')